! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! The ODE Jacobian of Chemical Model File
! 
! Generated by KPP-2.1 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : redhc_made_soa_vbs_Jacobian.f90
! Time                 : Wed Oct 28 17:42:24 2020
! Working directory    : /mnt/lfs1/BMC/fim/Jordan/models/rapid-refresh/WRFV3.9_RAPCHEM_v7/chem/KPP/mechanisms/redhc_made_soa_vbs
! Equation file        : redhc_made_soa_vbs.kpp
! Output root filename : redhc_made_soa_vbs
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE redhc_made_soa_vbs_Jacobian

  USE redhc_made_soa_vbs_Parameters
  USE redhc_made_soa_vbs_JacobianSP

  IMPLICIT NONE

CONTAINS


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Jac_SP_Vec - function for sparse multiplication: sparse Jacobian times vector
!   Arguments :
!      JVS       - sparse Jacobian of variables
!      UV        - User vector for variables
!      JUV       - Jacobian times user vector
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Jac_SP_Vec ( JVS, UV, JUV )

! JVS - sparse Jacobian of variables
  REAL(kind=dp) :: JVS(LU_NONZERO)
! UV - User vector for variables
  REAL(kind=dp) :: UV(NVAR)
! JUV - Jacobian times user vector
  REAL(kind=dp) :: JUV(NVAR)

  JUV(1) = JVS(1)*UV(1)+JVS(2)*UV(43)
  JUV(2) = JVS(3)*UV(2)+JVS(4)*UV(43)
  JUV(3) = JVS(5)*UV(3)+JVS(6)*UV(4)+JVS(7)*UV(43)
  JUV(4) = JVS(8)*UV(4)+JVS(9)*UV(5)+JVS(10)*UV(43)
  JUV(5) = JVS(11)*UV(5)+JVS(12)*UV(6)+JVS(13)*UV(43)
  JUV(6) = JVS(14)*UV(6)+JVS(15)*UV(43)
  JUV(7) = JVS(16)*UV(7)+JVS(17)*UV(8)+JVS(18)*UV(15)+JVS(19)*UV(43)
  JUV(8) = JVS(20)*UV(8)+JVS(21)*UV(9)+JVS(22)*UV(14)+JVS(23)*UV(43)
  JUV(9) = JVS(24)*UV(9)+JVS(25)*UV(10)+JVS(26)*UV(13)+JVS(27)*UV(43)
  JUV(10) = JVS(28)*UV(10)+JVS(29)*UV(11)+JVS(30)*UV(12)+JVS(31)*UV(43)
  JUV(11) = JVS(32)*UV(11)+JVS(33)*UV(43)
  JUV(12) = JVS(34)*UV(12)+JVS(35)*UV(43)
  JUV(13) = JVS(36)*UV(13)+JVS(37)*UV(43)
  JUV(14) = JVS(38)*UV(14)+JVS(39)*UV(43)
  JUV(15) = JVS(40)*UV(15)+JVS(41)*UV(43)
  JUV(16) = JVS(42)*UV(16)+JVS(43)*UV(17)+JVS(44)*UV(43)
  JUV(17) = JVS(45)*UV(17)+JVS(46)*UV(43)
  JUV(18) = JVS(47)*UV(18)+JVS(48)*UV(43)
  JUV(19) = JVS(49)*UV(19)+JVS(50)*UV(43)+JVS(51)*UV(44)
  JUV(20) = JVS(52)*UV(20)+JVS(53)*UV(46)+JVS(54)*UV(47)
  JUV(21) = JVS(55)*UV(21)+JVS(56)*UV(46)+JVS(57)*UV(48)
  JUV(22) = JVS(58)*UV(22)+JVS(59)*UV(24)+JVS(60)*UV(34)+JVS(61)*UV(37)+JVS(62)*UV(42)+JVS(63)*UV(43)+JVS(64)*UV(48)
  JUV(23) = JVS(65)*UV(23)+JVS(66)*UV(43)
  JUV(24) = JVS(67)*UV(24)+JVS(68)*UV(34)+JVS(69)*UV(43)
  JUV(25) = JVS(70)*UV(25)+JVS(71)*UV(40)+JVS(72)*UV(41)+JVS(73)*UV(43)+JVS(74)*UV(44)+JVS(75)*UV(47)
  JUV(26) = JVS(76)*UV(26)+JVS(77)*UV(43)+JVS(78)*UV(44)+JVS(79)*UV(46)
  JUV(27) = JVS(80)*UV(27)+JVS(81)*UV(42)+JVS(82)*UV(43)
  JUV(28) = JVS(83)*UV(28)+JVS(84)*UV(38)+JVS(85)*UV(39)+JVS(86)*UV(43)+JVS(87)*UV(46)+JVS(88)*UV(48)
  JUV(29) = JVS(89)*UV(23)+JVS(90)*UV(27)+JVS(91)*UV(29)+JVS(92)*UV(30)+JVS(93)*UV(32)+JVS(94)*UV(35)+JVS(95)*UV(36)&
              &+JVS(96)*UV(37)+JVS(97)*UV(38)+JVS(98)*UV(39)+JVS(99)*UV(42)+JVS(100)*UV(43)+JVS(101)*UV(48)
  JUV(30) = JVS(102)*UV(23)+JVS(103)*UV(30)+JVS(104)*UV(33)+JVS(105)*UV(36)+JVS(106)*UV(42)+JVS(107)*UV(43)+JVS(108)&
              &*UV(48)
  JUV(31) = JVS(109)*UV(31)+JVS(110)*UV(32)+JVS(111)*UV(35)+JVS(112)*UV(36)+JVS(113)*UV(40)+JVS(114)*UV(43)+JVS(115)&
              &*UV(45)+JVS(116)*UV(48)
  JUV(32) = JVS(117)*UV(32)+JVS(118)*UV(42)+JVS(119)*UV(43)+JVS(120)*UV(48)
  JUV(33) = JVS(121)*UV(33)+JVS(122)*UV(42)+JVS(123)*UV(43)+JVS(124)*UV(48)
  JUV(34) = JVS(125)*UV(22)+JVS(127)*UV(32)+JVS(128)*UV(33)+JVS(129)*UV(34)+JVS(130)*UV(35)+JVS(131)*UV(36)+JVS(133)&
              &*UV(42)+JVS(134)*UV(43)
  JUV(35) = JVS(136)*UV(35)+JVS(137)*UV(42)+JVS(138)*UV(43)+JVS(139)*UV(48)
  JUV(36) = JVS(140)*UV(36)+JVS(141)*UV(42)+JVS(142)*UV(43)+JVS(143)*UV(48)
  JUV(37) = JVS(144)*UV(33)+JVS(145)*UV(36)+JVS(146)*UV(37)+JVS(147)*UV(42)+JVS(148)*UV(43)+JVS(149)*UV(48)
  JUV(38) = JVS(150)*UV(24)+JVS(151)*UV(27)+JVS(152)*UV(32)+JVS(153)*UV(33)+JVS(154)*UV(34)+JVS(155)*UV(35)+JVS(156)&
              &*UV(36)+JVS(157)*UV(37)+JVS(158)*UV(38)+JVS(159)*UV(42)+JVS(160)*UV(43)+JVS(161)*UV(48)
  JUV(39) = JVS(162)*UV(27)+JVS(163)*UV(32)+JVS(164)*UV(33)+JVS(165)*UV(35)+JVS(166)*UV(36)+JVS(167)*UV(37)+JVS(168)&
              &*UV(38)+JVS(169)*UV(39)+JVS(170)*UV(42)+JVS(171)*UV(43)+JVS(172)*UV(44)+JVS(173)*UV(45)+JVS(174)*UV(47)&
              &+JVS(175)*UV(48)
  JUV(40) = JVS(176)*UV(23)+JVS(177)*UV(32)+JVS(178)*UV(33)+JVS(179)*UV(34)+JVS(180)*UV(35)+JVS(181)*UV(36)+JVS(182)&
              &*UV(37)+JVS(183)*UV(40)+JVS(184)*UV(42)+JVS(185)*UV(43)+JVS(186)*UV(44)+JVS(187)*UV(45)+JVS(188)*UV(48)
  JUV(41) = JVS(189)*UV(23)+JVS(190)*UV(24)+JVS(191)*UV(25)+JVS(192)*UV(27)+JVS(193)*UV(30)+JVS(194)*UV(31)+JVS(195)&
              &*UV(32)+JVS(196)*UV(33)+JVS(197)*UV(34)+JVS(198)*UV(35)+JVS(199)*UV(36)+JVS(200)*UV(37)+JVS(201)*UV(38)&
              &+JVS(203)*UV(41)+JVS(204)*UV(42)+JVS(205)*UV(43)+JVS(206)*UV(44)+JVS(207)*UV(45)+JVS(208)*UV(47)+JVS(209)&
              &*UV(48)
  JUV(42) = JVS(210)*UV(27)+JVS(211)*UV(32)+JVS(212)*UV(33)+JVS(213)*UV(35)+JVS(214)*UV(36)+JVS(215)*UV(37)+JVS(216)&
              &*UV(42)+JVS(217)*UV(43)+JVS(218)*UV(44)+JVS(219)*UV(45)+JVS(220)*UV(46)+JVS(221)*UV(48)
  JUV(43) = JVS(222)*UV(17)+JVS(223)*UV(18)+JVS(224)*UV(19)+JVS(225)*UV(23)+JVS(226)*UV(25)+JVS(227)*UV(26)+JVS(228)&
              &*UV(27)+JVS(229)*UV(28)+JVS(230)*UV(29)+JVS(231)*UV(30)+JVS(232)*UV(31)+JVS(233)*UV(32)+JVS(234)*UV(33)&
              &+JVS(235)*UV(34)+JVS(236)*UV(35)+JVS(237)*UV(36)+JVS(238)*UV(37)+JVS(239)*UV(38)+JVS(240)*UV(39)+JVS(243)&
              &*UV(42)+JVS(244)*UV(43)+JVS(245)*UV(44)+JVS(246)*UV(45)+JVS(247)*UV(46)+JVS(248)*UV(47)+JVS(249)*UV(48)
  JUV(44) = JVS(250)*UV(19)+JVS(251)*UV(23)+JVS(252)*UV(24)+JVS(253)*UV(26)+JVS(254)*UV(27)+JVS(255)*UV(29)+JVS(256)&
              &*UV(30)+JVS(257)*UV(31)+JVS(258)*UV(32)+JVS(260)*UV(34)+JVS(261)*UV(35)+JVS(262)*UV(36)+JVS(263)*UV(37)&
              &+JVS(264)*UV(38)+JVS(265)*UV(39)+JVS(266)*UV(40)+JVS(267)*UV(41)+JVS(268)*UV(42)+JVS(269)*UV(43)+JVS(270)&
              &*UV(44)+JVS(271)*UV(45)+JVS(272)*UV(46)+JVS(273)*UV(47)+JVS(274)*UV(48)
  JUV(45) = JVS(275)*UV(40)+JVS(276)*UV(41)+JVS(277)*UV(42)+JVS(279)*UV(44)+JVS(280)*UV(45)+JVS(281)*UV(46)+JVS(282)&
              &*UV(47)+JVS(283)*UV(48)
  JUV(46) = JVS(284)*UV(20)+JVS(285)*UV(21)+JVS(286)*UV(26)+JVS(287)*UV(28)+JVS(288)*UV(31)+JVS(290)*UV(35)+JVS(291)&
              &*UV(36)+JVS(292)*UV(37)+JVS(296)*UV(41)+JVS(297)*UV(42)+JVS(298)*UV(43)+JVS(299)*UV(44)+JVS(300)*UV(45)&
              &+JVS(301)*UV(46)+JVS(302)*UV(47)+JVS(303)*UV(48)
  JUV(47) = JVS(304)*UV(20)+JVS(305)*UV(23)+JVS(306)*UV(30)+JVS(308)*UV(35)+JVS(309)*UV(36)+JVS(310)*UV(38)+JVS(311)&
              &*UV(42)+JVS(312)*UV(43)+JVS(313)*UV(44)+JVS(314)*UV(45)+JVS(315)*UV(46)+JVS(316)*UV(47)+JVS(317)*UV(48)
  JUV(48) = JVS(318)*UV(21)+JVS(319)*UV(26)+JVS(320)*UV(28)+JVS(321)*UV(32)+JVS(322)*UV(33)+JVS(323)*UV(35)+JVS(324)&
              &*UV(36)+JVS(325)*UV(37)+JVS(326)*UV(38)+JVS(327)*UV(39)+JVS(328)*UV(42)+JVS(329)*UV(43)+JVS(330)*UV(44)&
              &+JVS(331)*UV(45)+JVS(332)*UV(46)+JVS(334)*UV(48)
      
END SUBROUTINE Jac_SP_Vec

! End of Jac_SP_Vec function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! JacTR_SP_Vec - sparse multiplication: sparse Jacobian transposed times vector
!   Arguments :
!      JVS       - sparse Jacobian of variables
!      UV        - User vector for variables
!      JTUV      - Jacobian transposed times user vector
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE JacTR_SP_Vec ( JVS, UV, JTUV )

! JVS - sparse Jacobian of variables
  REAL(kind=dp) :: JVS(LU_NONZERO)
! UV - User vector for variables
  REAL(kind=dp) :: UV(NVAR)
! JTUV - Jacobian transposed times user vector
  REAL(kind=dp) :: JTUV(NVAR)

  JTUV(1) = JVS(1)*UV(1)
  JTUV(2) = JVS(3)*UV(2)
  JTUV(3) = JVS(5)*UV(3)
  JTUV(4) = JVS(6)*UV(3)+JVS(8)*UV(4)
  JTUV(5) = JVS(9)*UV(4)+JVS(11)*UV(5)
  JTUV(6) = JVS(12)*UV(5)+JVS(14)*UV(6)
  JTUV(7) = JVS(16)*UV(7)
  JTUV(8) = JVS(17)*UV(7)+JVS(20)*UV(8)
  JTUV(9) = JVS(21)*UV(8)+JVS(24)*UV(9)
  JTUV(10) = JVS(25)*UV(9)+JVS(28)*UV(10)
  JTUV(11) = JVS(29)*UV(10)+JVS(32)*UV(11)
  JTUV(12) = JVS(30)*UV(10)+JVS(34)*UV(12)
  JTUV(13) = JVS(26)*UV(9)+JVS(36)*UV(13)
  JTUV(14) = JVS(22)*UV(8)+JVS(38)*UV(14)
  JTUV(15) = JVS(18)*UV(7)+JVS(40)*UV(15)
  JTUV(16) = JVS(42)*UV(16)
  JTUV(17) = JVS(43)*UV(16)+JVS(45)*UV(17)+JVS(222)*UV(43)
  JTUV(18) = JVS(47)*UV(18)+JVS(223)*UV(43)
  JTUV(19) = JVS(49)*UV(19)+JVS(224)*UV(43)+JVS(250)*UV(44)
  JTUV(20) = JVS(52)*UV(20)+JVS(284)*UV(46)+JVS(304)*UV(47)
  JTUV(21) = JVS(55)*UV(21)+JVS(285)*UV(46)+JVS(318)*UV(48)
  JTUV(22) = JVS(58)*UV(22)+JVS(125)*UV(34)
  JTUV(23) = JVS(65)*UV(23)+JVS(89)*UV(29)+JVS(102)*UV(30)+JVS(176)*UV(40)+JVS(189)*UV(41)+JVS(225)*UV(43)+JVS(251)&
               &*UV(44)+JVS(305)*UV(47)
  JTUV(24) = JVS(59)*UV(22)+JVS(67)*UV(24)+JVS(150)*UV(38)+JVS(190)*UV(41)+JVS(252)*UV(44)
  JTUV(25) = JVS(70)*UV(25)+JVS(191)*UV(41)+JVS(226)*UV(43)
  JTUV(26) = JVS(76)*UV(26)+JVS(227)*UV(43)+JVS(253)*UV(44)+JVS(286)*UV(46)+JVS(319)*UV(48)
  JTUV(27) = JVS(80)*UV(27)+JVS(90)*UV(29)+JVS(151)*UV(38)+JVS(162)*UV(39)+JVS(192)*UV(41)+JVS(210)*UV(42)+JVS(228)&
               &*UV(43)+JVS(254)*UV(44)
  JTUV(28) = JVS(83)*UV(28)+JVS(229)*UV(43)+JVS(287)*UV(46)+JVS(320)*UV(48)
  JTUV(29) = JVS(91)*UV(29)+JVS(230)*UV(43)+JVS(255)*UV(44)
  JTUV(30) = JVS(92)*UV(29)+JVS(103)*UV(30)+JVS(193)*UV(41)+JVS(231)*UV(43)+JVS(256)*UV(44)+JVS(306)*UV(47)
  JTUV(31) = JVS(109)*UV(31)+JVS(194)*UV(41)+JVS(232)*UV(43)+JVS(257)*UV(44)+JVS(288)*UV(46)
  JTUV(32) = JVS(93)*UV(29)+JVS(110)*UV(31)+JVS(117)*UV(32)+JVS(127)*UV(34)+JVS(152)*UV(38)+JVS(163)*UV(39)+JVS(177)&
               &*UV(40)+JVS(195)*UV(41)+JVS(211)*UV(42)+JVS(233)*UV(43)+JVS(258)*UV(44)+JVS(321)*UV(48)
  JTUV(33) = JVS(104)*UV(30)+JVS(121)*UV(33)+JVS(128)*UV(34)+JVS(144)*UV(37)+JVS(153)*UV(38)+JVS(164)*UV(39)+JVS(178)&
               &*UV(40)+JVS(196)*UV(41)+JVS(212)*UV(42)+JVS(234)*UV(43)+JVS(322)*UV(48)
  JTUV(34) = JVS(60)*UV(22)+JVS(68)*UV(24)+JVS(129)*UV(34)+JVS(154)*UV(38)+JVS(179)*UV(40)+JVS(197)*UV(41)+JVS(235)&
               &*UV(43)+JVS(260)*UV(44)
  JTUV(35) = JVS(94)*UV(29)+JVS(111)*UV(31)+JVS(130)*UV(34)+JVS(136)*UV(35)+JVS(155)*UV(38)+JVS(165)*UV(39)+JVS(180)&
               &*UV(40)+JVS(198)*UV(41)+JVS(213)*UV(42)+JVS(236)*UV(43)+JVS(261)*UV(44)+JVS(290)*UV(46)+JVS(308)*UV(47)&
               &+JVS(323)*UV(48)
  JTUV(36) = JVS(95)*UV(29)+JVS(105)*UV(30)+JVS(112)*UV(31)+JVS(131)*UV(34)+JVS(140)*UV(36)+JVS(145)*UV(37)+JVS(156)&
               &*UV(38)+JVS(166)*UV(39)+JVS(181)*UV(40)+JVS(199)*UV(41)+JVS(214)*UV(42)+JVS(237)*UV(43)+JVS(262)*UV(44)&
               &+JVS(291)*UV(46)+JVS(309)*UV(47)+JVS(324)*UV(48)
  JTUV(37) = JVS(61)*UV(22)+JVS(96)*UV(29)+JVS(146)*UV(37)+JVS(157)*UV(38)+JVS(167)*UV(39)+JVS(182)*UV(40)+JVS(200)&
               &*UV(41)+JVS(215)*UV(42)+JVS(238)*UV(43)+JVS(263)*UV(44)+JVS(292)*UV(46)+JVS(325)*UV(48)
  JTUV(38) = JVS(84)*UV(28)+JVS(97)*UV(29)+JVS(158)*UV(38)+JVS(168)*UV(39)+JVS(201)*UV(41)+JVS(239)*UV(43)+JVS(264)&
               &*UV(44)+JVS(310)*UV(47)+JVS(326)*UV(48)
  JTUV(39) = JVS(85)*UV(28)+JVS(98)*UV(29)+JVS(169)*UV(39)+JVS(240)*UV(43)+JVS(265)*UV(44)+JVS(327)*UV(48)
  JTUV(40) = JVS(71)*UV(25)+JVS(113)*UV(31)+JVS(183)*UV(40)+JVS(266)*UV(44)+JVS(275)*UV(45)
  JTUV(41) = JVS(72)*UV(25)+JVS(203)*UV(41)+JVS(267)*UV(44)+JVS(276)*UV(45)+JVS(296)*UV(46)
  JTUV(42) = JVS(62)*UV(22)+JVS(81)*UV(27)+JVS(99)*UV(29)+JVS(106)*UV(30)+JVS(118)*UV(32)+JVS(122)*UV(33)+JVS(133)&
               &*UV(34)+JVS(137)*UV(35)+JVS(141)*UV(36)+JVS(147)*UV(37)+JVS(159)*UV(38)+JVS(170)*UV(39)+JVS(184)*UV(40)&
               &+JVS(204)*UV(41)+JVS(216)*UV(42)+JVS(243)*UV(43)+JVS(268)*UV(44)+JVS(277)*UV(45)+JVS(297)*UV(46)+JVS(311)&
               &*UV(47)+JVS(328)*UV(48)
  JTUV(43) = JVS(2)*UV(1)+JVS(4)*UV(2)+JVS(7)*UV(3)+JVS(10)*UV(4)+JVS(13)*UV(5)+JVS(15)*UV(6)+JVS(19)*UV(7)+JVS(23)&
               &*UV(8)+JVS(27)*UV(9)+JVS(31)*UV(10)+JVS(33)*UV(11)+JVS(35)*UV(12)+JVS(37)*UV(13)+JVS(39)*UV(14)+JVS(41)&
               &*UV(15)+JVS(44)*UV(16)+JVS(46)*UV(17)+JVS(48)*UV(18)+JVS(50)*UV(19)+JVS(63)*UV(22)+JVS(66)*UV(23)+JVS(69)&
               &*UV(24)+JVS(73)*UV(25)+JVS(77)*UV(26)+JVS(82)*UV(27)+JVS(86)*UV(28)+JVS(100)*UV(29)+JVS(107)*UV(30)+JVS(114)&
               &*UV(31)+JVS(119)*UV(32)+JVS(123)*UV(33)+JVS(134)*UV(34)+JVS(138)*UV(35)+JVS(142)*UV(36)+JVS(148)*UV(37)&
               &+JVS(160)*UV(38)+JVS(171)*UV(39)+JVS(185)*UV(40)+JVS(205)*UV(41)+JVS(217)*UV(42)+JVS(244)*UV(43)+JVS(269)&
               &*UV(44)+JVS(298)*UV(46)+JVS(312)*UV(47)+JVS(329)*UV(48)
  JTUV(44) = JVS(51)*UV(19)+JVS(74)*UV(25)+JVS(78)*UV(26)+JVS(172)*UV(39)+JVS(186)*UV(40)+JVS(206)*UV(41)+JVS(218)&
               &*UV(42)+JVS(245)*UV(43)+JVS(270)*UV(44)+JVS(279)*UV(45)+JVS(299)*UV(46)+JVS(313)*UV(47)+JVS(330)*UV(48)
  JTUV(45) = JVS(115)*UV(31)+JVS(173)*UV(39)+JVS(187)*UV(40)+JVS(207)*UV(41)+JVS(219)*UV(42)+JVS(246)*UV(43)+JVS(271)&
               &*UV(44)+JVS(280)*UV(45)+JVS(300)*UV(46)+JVS(314)*UV(47)+JVS(331)*UV(48)
  JTUV(46) = JVS(53)*UV(20)+JVS(56)*UV(21)+JVS(79)*UV(26)+JVS(87)*UV(28)+JVS(220)*UV(42)+JVS(247)*UV(43)+JVS(272)*UV(44)&
               &+JVS(281)*UV(45)+JVS(301)*UV(46)+JVS(315)*UV(47)+JVS(332)*UV(48)
  JTUV(47) = JVS(54)*UV(20)+JVS(75)*UV(25)+JVS(174)*UV(39)+JVS(208)*UV(41)+JVS(248)*UV(43)+JVS(273)*UV(44)+JVS(282)&
               &*UV(45)+JVS(302)*UV(46)+JVS(316)*UV(47)
  JTUV(48) = JVS(57)*UV(21)+JVS(64)*UV(22)+JVS(88)*UV(28)+JVS(101)*UV(29)+JVS(108)*UV(30)+JVS(116)*UV(31)+JVS(120)&
               &*UV(32)+JVS(124)*UV(33)+JVS(139)*UV(35)+JVS(143)*UV(36)+JVS(149)*UV(37)+JVS(161)*UV(38)+JVS(175)*UV(39)&
               &+JVS(188)*UV(40)+JVS(209)*UV(41)+JVS(221)*UV(42)+JVS(249)*UV(43)+JVS(274)*UV(44)+JVS(283)*UV(45)+JVS(303)&
               &*UV(46)+JVS(317)*UV(47)+JVS(334)*UV(48)
      
END SUBROUTINE JacTR_SP_Vec

! End of JacTR_SP_Vec function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE redhc_made_soa_vbs_Jacobian

