! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! The Reaction Rates File
! 
! Generated by KPP-2.1 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : redhc_made_soa_vbs_Rates.f90
! Time                 : Wed Oct 28 17:42:24 2020
! Working directory    : /mnt/lfs1/BMC/fim/Jordan/models/rapid-refresh/WRFV3.9_RAPCHEM_v7/chem/KPP/mechanisms/redhc_made_soa_vbs
! Equation file        : redhc_made_soa_vbs.kpp
! Output root filename : redhc_made_soa_vbs
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE redhc_made_soa_vbs_Rates

  USE redhc_made_soa_vbs_Parameters
  USE redhc_made_soa_vbs_Global
  IMPLICIT NONE

CONTAINS



! Begin Rate Law Functions from KPP_HOME/util/UserRateLaws

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!  User-defined Rate Law functions
!  Note: the default argument type for rate laws, as read from the equations file, is single precision
!        but all the internal calculations are performed in double precision
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

!~~~>  Arrhenius
   REAL(kind=dp) FUNCTION ARR( A0,B0,C0 )
      REAL A0,B0,C0      
      ARR =  DBLE(A0) * EXP(-DBLE(B0)/TEMP) * (TEMP/300.0_dp)**DBLE(C0)
   END FUNCTION ARR        

!~~~> Simplified Arrhenius, with two arguments
!~~~> Note: The argument B0 has a changed sign when compared to ARR
   REAL(kind=dp) FUNCTION ARR2( A0,B0 )
      REAL A0,B0           
      ARR2 =  DBLE(A0) * EXP( DBLE(B0)/TEMP )              
   END FUNCTION ARR2          

   REAL(kind=dp) FUNCTION EP2(A0,C0,A2,C2,A3,C3)
      REAL A0,C0,A2,C2,A3,C3
      REAL(dp) K0,K2,K3            
      K0 = DBLE(A0) * EXP(-DBLE(C0)/TEMP)
      K2 = DBLE(A2) * EXP(-DBLE(C2)/TEMP)
      K3 = DBLE(A3) * EXP(-DBLE(C3)/TEMP)
      K3 = K3*CFACTOR*1.0E6_dp
      EP2 = K0 + K3/(1.0_dp+K3/K2 )
   END FUNCTION EP2

   REAL(kind=dp) FUNCTION EP3(A1,C1,A2,C2) 
      REAL A1, C1, A2, C2
      REAL(dp) K1, K2      
      K1 = DBLE(A1) * EXP(-DBLE(C1)/TEMP)
      K2 = DBLE(A2) * EXP(-DBLE(C2)/TEMP)
      EP3 = K1 + K2*(1.0E6_dp*CFACTOR)
   END FUNCTION EP3 

   REAL(kind=dp) FUNCTION FALL ( A0,B0,C0,A1,B1,C1,CF)
      REAL A0,B0,C0,A1,B1,C1,CF
      REAL(dp) K0, K1     
      K0 = DBLE(A0) * EXP(-DBLE(B0)/TEMP)* (TEMP/300.0_dp)**DBLE(C0)
      K1 = DBLE(A1) * EXP(-DBLE(B1)/TEMP)* (TEMP/300.0_dp)**DBLE(C1)
      K0 = K0*CFACTOR*1.0E6_dp
      K1 = K0/K1
      FALL = (K0/(1.0_dp+K1))*   &
           DBLE(CF)**(1.0_dp/(1.0_dp+(LOG10(K1))**2))
   END FUNCTION FALL

  !---------------------------------------------------------------------------

  ELEMENTAL REAL(dp) FUNCTION k_3rd(temp,cair,k0_300K,n,kinf_300K,m,fc)

    INTRINSIC LOG10

    REAL(dp), INTENT(IN) :: temp      ! temperature [K]
    REAL(dp), INTENT(IN) :: cair      ! air concentration [molecules/cm3]
    REAL,     INTENT(IN) :: k0_300K   ! low pressure limit at 300 K
    REAL,     INTENT(IN) :: n         ! exponent for low pressure limit
    REAL,     INTENT(IN) :: kinf_300K ! high pressure limit at 300 K
    REAL,     INTENT(IN) :: m         ! exponent for high pressure limit
    REAL,     INTENT(IN) :: fc        ! broadening factor (usually fc=0.6)
    REAL                 :: zt_help, k0_T, kinf_T, k_ratio

    zt_help = 300._dp/temp
    k0_T    = k0_300K   * zt_help**(n) * cair ! k_0   at current T
    kinf_T  = kinf_300K * zt_help**(m)        ! k_inf at current T
    k_ratio = k0_T/kinf_T
    k_3rd   = k0_T/(1._dp+k_ratio)*fc**(1._dp/(1._dp+LOG10(k_ratio)**2))

  END FUNCTION k_3rd

  !---------------------------------------------------------------------------

  ELEMENTAL REAL(dp) FUNCTION k_arr (k_298,tdep,temp)
    ! Arrhenius function

    REAL,     INTENT(IN) :: k_298 ! k at T = 298.15K
    REAL,     INTENT(IN) :: tdep  ! temperature dependence
    REAL(dp), INTENT(IN) :: temp  ! temperature

    INTRINSIC EXP

    k_arr = k_298 * EXP(tdep*(1._dp/temp-3.3540E-3_dp)) ! 1/298.15=3.3540e-3

  END FUNCTION k_arr

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!  End of User-defined Rate Law functions
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

! End Rate Law Functions from KPP_HOME/util/UserRateLaws


! Begin INLINED Rate Law Functions




REAL(KIND=dp) FUNCTION usro3j2oh(temp,c_m,c_h2o)
   
   REAL(KIND=dp), INTENT(IN) :: temp, c_m, c_h2o
   REAL(KIND=dp) :: kh2o,kn2,ko2

   kh2o = 2.2e-10_dp
   kn2  = 0.79_dp * ARR2(1.8e-11_dp,-110.0_dp, temp) 
   ko2  = 0.21_dp * ARR2(3.2e-11_dp, -70.0_dp, temp)

   usro3j2oh = (kh2o*c_h2o) / (kh2o*c_h2o + kn2*c_m + ko2*c_m)

END FUNCTION usro3j2oh




REAL(KIND=dp) FUNCTION TROEMS(k0_300K,n,kinf_300K,m,TEMP,C_M)

    INTRINSIC LOG10

    REAL(KIND=dp), INTENT(IN) :: TEMP      ! TEMPerature [K]
    REAL(KIND=dp), INTENT(IN) :: C_M      ! air concentration [molecules/cm3]
    REAL(KIND=dp), INTENT(IN) :: k0_300K   ! low pressure limit at 300 K
    REAL(KIND=dp), INTENT(IN) :: n         ! exponent for low pressure limit
    REAL(KIND=dp), INTENT(IN) :: kinf_300K ! high pressure limit at 300 K
    REAL(KIND=dp), INTENT(IN) :: m         ! exponent for high pressure limit
    REAL(KIND=dp)             :: zt_help, k0_T, kinf_T, k_ratio

    zt_help = TEMP/300._dp
    k0_T    = k0_300K   * zt_help**(n) * C_M ! k_0   at current T
    kinf_T  = kinf_300K * zt_help**(m)        ! k_inf at current T
    k_ratio = k0_T/kinf_T
    TROEMS   = k0_T/(1._dp+k_ratio)*0.6_dp**(1._dp/(1._dp+LOG10(k_ratio)**2))

END FUNCTION TROEMS


REAL(KIND=dp) FUNCTION usr5( temp, c_m )

    REAL(KIND=dp), INTENT(IN) :: temp
    REAL(KIND=dp), INTENT(IN) :: c_m

    REAL(KIND=dp) :: k0, k2

   k0 = c_m * 6.5e-34_dp * exp( 1335._dp/temp )
   k2 = exp( 2199._dp/temp )
   k0 = k0 /(1.0_dp + k0/(2.7e-11_dp*k2))
   k2 = exp( 460._dp/temp )

   usr5 = k0 + 2.4e-14_dp * k2

END FUNCTION usr5

REAL(KIND=dp) FUNCTION usr8( temp, c_m )

    REAL(KIND=dp), INTENT(IN) :: temp
    REAL(KIND=dp), INTENT(IN) :: c_m

    REAL(KIND=dp), parameter :: boltz = 1.38044e-16_dp

    usr8 = 1.5e-13_dp * (1._dp + 6.e-7_dp*boltz*c_m*temp)

END FUNCTION usr8

REAL(KIND=dp) FUNCTION usr9( temp, c_m, c_h2o )

    REAL(KIND=dp), INTENT(IN) :: temp
    REAL(KIND=dp), INTENT(IN) :: c_m
    REAL(KIND=dp), INTENT(IN) :: c_h2o

    REAL(KIND=dp) :: ko, kinf, fc

    if( c_h2o > 0._dp ) then
       ko   = 2.3e-13_dp * exp( 600._dp/temp )
       kinf = 1.7e-33_dp * c_m * exp( 1000._dp/temp )
       fc   = 1._dp/c_h2o + 1.4e-21_dp * exp( 2200._dp/temp )
       usr9 = (ko + kinf) * fc
    else
       usr9 = 0._dp
    end if

END FUNCTION usr9

REAL(KIND=dp) FUNCTION usr16( rh, temp )

    REAL(KIND=dp), INTENT(IN) :: rh                       ! relative humidity
    REAL(KIND=dp), INTENT(IN) :: temp                     ! temperature (K)


    usr16 = 0._dp

END FUNCTION usr16

REAL(KIND=dp) FUNCTION usr17( rh, temp )

    REAL(KIND=dp), INTENT(IN) :: rh                       ! relative humidity
    REAL(KIND=dp), INTENT(IN) :: temp                     ! temperature (K)

    usr17 = 0._dp

END FUNCTION usr17

REAL(KIND=dp) FUNCTION usr17a( rh, temp )

    REAL(KIND=dp), INTENT(IN) :: rh                       ! relative humidity
    REAL(KIND=dp), INTENT(IN) :: temp                     ! temperature (K)

    usr17a = 0._dp

END FUNCTION usr17a

REAL(KIND=dp) FUNCTION usr23( temp, c_m )

    REAL(KIND=dp), INTENT(IN) :: temp
    REAL(KIND=dp), INTENT(IN) :: c_m

    REAL(KIND=dp) :: fc, k0
    REAL(KIND=dp) :: wrk

    fc    = 3.e-11_dp * (300._dp/temp) ** 3.3_dp
    wrk   = fc * c_m
    k0    = wrk / (1._dp + wrk/1.5e-12_dp)
    usr23 = k0 * .6_dp ** (1._dp/(1._dp + (log10( wrk/1.5e-12_dp ))**2._dp))

END FUNCTION usr23

REAL(KIND=dp) FUNCTION usr24( temp, c_m )

    REAL(KIND=dp), INTENT(IN) :: temp
    REAL(KIND=dp), INTENT(IN) :: c_m

    REAL(KIND=dp) :: ko, wrk

    wrk   = .21_dp*c_m
    ko    = 1._dp + 5.5e-31_dp*exp( 7460._dp/temp )*wrk
    usr24 = 1.7e-42_dp*exp( 7810._dp/temp )*wrk/ko

END FUNCTION usr24

REAL(KIND=dp) FUNCTION usr_c2o3_no2( c_m )

    REAL(KIND=dp), INTENT(IN) :: c_m

    REAL(KIND=dp) :: ko, kinf, wrk

    ko    = 2.6e-28_dp * c_m
    kinf  = 1.2e-11_dp
    wrk   = ko/kinf
    usr_c2o3_no2 = (ko/(1._dp+wrk))*.6_dp**(1._dp/(1._dp+(log10(wrk))**2))

END FUNCTION usr_c2o3_no2

REAL(KIND=dp) FUNCTION usr_xo2n_ho2( temp )

    REAL(KIND=dp), INTENT(IN) :: temp

    REAL(KIND=dp) :: rxn_xo2_no, rxn_xo2n_no, rxn_xo2_ho2

    rxn_xo2_no  = ARR2( 4.2e-12_dp, -180._dp, temp )
    rxn_xo2n_no = 6.8e-13_dp
    rxn_xo2_ho2 = ARR2( 3.5e-13_dp, -1000._dp, temp )
    usr_xo2n_ho2 = rxn_xo2n_no * rxn_xo2_ho2 / (rxn_xo2_no + 1.e-36_dp)

END FUNCTION usr_xo2n_ho2

REAL(KIND=dp) FUNCTION usr26( rh, temp )

    REAL(KIND=dp), INTENT(IN) :: rh                       ! relative humidity
    REAL(KIND=dp), INTENT(IN) :: temp                     ! temperature (K)

    usr26 = 0._dp

END FUNCTION usr26




! End INLINED Rate Law Functions

! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_SUN - update SUN light using TIME
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  SUBROUTINE Update_SUN()
      !USE redhc_made_soa_vbs_Parameters
      !USE redhc_made_soa_vbs_Global

    IMPLICIT NONE

    REAL(kind=dp) SunRise, SunSet
    REAL(kind=dp) Thour, Tlocal, Ttmp 
   
    SunRise = 4.5_dp 
    SunSet  = 19.5_dp 
    Thour = TIME/3600.0_dp 
    Tlocal = Thour - (INT(Thour)/24)*24

    IF ((Tlocal>=SunRise).AND.(Tlocal<=SunSet)) THEN
       Ttmp = (2.0*Tlocal-SunRise-SunSet)/(SunSet-SunRise)
       IF (Ttmp.GT.0) THEN
          Ttmp =  Ttmp*Ttmp
       ELSE
          Ttmp = -Ttmp*Ttmp
       END IF
       SUN = ( 1.0_dp + COS(PI*Ttmp) )/2.0_dp 
    ELSE
       SUN = 0.0_dp 
    END IF

 END SUBROUTINE Update_SUN

! End of Update_SUN function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_RCONST - function to update rate constants
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Update_RCONST ( )




! Begin INLINED RCONST


! End INLINED RCONST

  RCONST(1) = (j(Pj_o31d)*usro3j2oh(temp,c_m,c_h2o))
  RCONST(2) = (j(Pj_no2))
  RCONST(3) = (j(Pj_n2o5))
  RCONST(4) = (j(Pj_hno3))
  RCONST(5) = (j(Pj_no3o))
  RCONST(6) = (j(Pj_hno4))
  RCONST(7) = (j(Pj_ch2or))
  RCONST(8) = (j(Pj_ch2om))
  RCONST(9) = (j(Pj_h2o2))
  RCONST(10) = (j(Pj_ch3cho))
  RCONST(11) = (j(Pj_ch3cocho))
  RCONST(12) = (j(Pj_pan))
  RCONST(13) = (j(Pj_ch3o2h))
  RCONST(14) = (j(Pj_ch3o2h))
  RCONST(15) = (ARR2(1.7e-12_dp,940.0_dp,TEMP))
  RCONST(16) = (ARR2(1.0e-14_dp,490.0_dp,TEMP))
  RCONST(17) = (usr9(temp,c_m,c_h2o))
  RCONST(18) = (ARR2(2.9e-12_dp,160.0_dp,TEMP))
  RCONST(19) = (ARR2(4.8e-11_dp,-250.0_dp,TEMP))
  RCONST(20) = (ARR2(4.2e-12_dp,240.0_dp,TEMP))
  RCONST(21) = (TROE(6.90e-31_dp,1.0_dp,2.60e-11_dp,0.0_dp,TEMP,C_M))
  RCONST(22) = (ARR2(3.5e-12_dp,-250.0_dp,TEMP))
  RCONST(23) = (ARR2(3.0e-12_dp,1500.0_dp,TEMP))
  RCONST(24) = (ARR2(1.2e-13_dp,2450.0_dp,TEMP))
  RCONST(25) = (ARR2(4.0e-12_dp,-170.0_dp,TEMP))
  RCONST(26) = (TROE(2.e-30_dp,4.4_dp,1.4e-12_dp,.7_dp,TEMP,C_M))
  RCONST(27) = (TROEE(3.333e26_dp,10900._dp,2.2e-30_dp,4.4_dp,1.4e-12_dp,.7_dp,TEMP,C_M))
  RCONST(28) = (TROE(2.e-30_dp,3._dp,2.5e-11_dp,0._dp,TEMP,C_M))
  RCONST(29) = (usr5(TEMP,C_M))
  RCONST(30) = (ARR2(1.5e-11_dp,-170._dp,TEMP))
  RCONST(31) = (TROE(1.8e-31_dp,3.2_dp,4.7e-12_dp,1.4_dp,TEMP,C_M))
  RCONST(32) = (ARR2(1.3e-12_dp,-380._dp,TEMP))
  RCONST(33) = (TROEE(4.76e26_dp,10900._dp,1.8e-31_dp,3.2_dp,4.7e-12_dp,1.4_dp,TEMP,C_M))
  RCONST(34) = (ARR2(6.e-13_dp,2058._dp,TEMP))
  RCONST(35) = (9.e-12_dp)
  RCONST(36) = (usr8(temp,c_m))
  RCONST(37) = (ARR2(1.1D+2,1710.0_dp,TEMP))
  RCONST(38) = (ARR2(7.e-12_dp,-250._dp,TEMP))
  RCONST(39) = (2.5e-15_dp)
  RCONST(40) = (ARR2(8.1e-12_dp,-270._dp,TEMP))
  RCONST(41) = (usr_c2o3_no2(c_m))
  RCONST(42) = (ARR2(2.e16_dp,13500._dp,TEMP))
  RCONST(43) = (2.e-12_dp)
  RCONST(44) = (6.5e-12_dp)
  RCONST(45) = (8.1e-13_dp)
  RCONST(46) = (ARR2(1.1e-15_dp,8000._dp,TEMP))
  RCONST(47) = (1.6e3_dp)
  RCONST(48) = (ARR2(5.2e-12_dp,-504._dp,TEMP))
  RCONST(49) = (ARR2(4.33e-15_dp,1800._dp,TEMP))
  RCONST(50) = (7.7e-15_dp)
  RCONST(51) = (ARR2(9.1e-15_dp,2850._dp,TEMP))
  RCONST(52) = (TROEMS(1.0D-28,-0.8_dp,8.8D-12,0.0_dp,TEMP,C_M))
  RCONST(53) = (1.5e-11_dp)
  RCONST(54) = (ARR2(2.54e-11_dp,-410._dp,TEMP))
  RCONST(55) = (ARR2(1.23e-14_dp,2013._dp,TEMP))
  RCONST(56) = (ARR2(3.03e-12_dp,446.0_dp,TEMP))
  RCONST(57) = (3.2e-12_dp)
  RCONST(58) = (ARR2(5.9e-13_dp,360._dp,TEMP))
  RCONST(59) = (ARR2(2.6e-12_dp,-365._dp,TEMP))
  RCONST(60) = (ARR2(1.7e-14_dp,-1300._dp,TEMP))
  RCONST(61) = (6.8e-13_dp)
  RCONST(62) = (ARR2(3.5e-13_dp,-1000._dp,TEMP))
  RCONST(63) = (usr_xo2n_ho2(TEMP))
  RCONST(64) = (8.e-11_dp)
  RCONST(65) = (usr23(TEMP,C_M))
  RCONST(66) = (ARR2(1.7e-12_dp,710._dp,TEMP))
  RCONST(67) = (5.5e-11_dp)
  RCONST(68) = (ARR2(1.2D-15,821.0_dp,TEMP))
  RCONST(69) = (ARR2(1.5D-11,-449.0_dp,TEMP))
  RCONST(70) = (ARR2(3.7D-12,-175.0_dp,TEMP))
  RCONST(71) = (5.60D-16)
  RCONST(72) = (2.52D-10)
  RCONST(73) = (2.20D-11)
  RCONST(74) = (ARR2(4.40D-15,845.0_dp,TEMP))
  RCONST(75) = (ARR2(1.33D-11,-500.0_dp,TEMP))
  RCONST(76) = (RATE_CVPOA)
  RCONST(77) = (RATE_CVPOA)
  RCONST(78) = (RATE_CVPOA)
  RCONST(79) = (RATE_CVPOA)
  RCONST(80) = (RATE_CVASOA)
  RCONST(81) = (RATE_CVASOA)
  RCONST(82) = (RATE_CVASOA)
  RCONST(83) = (RATE_CVASOA0)
  RCONST(84) = (RATE_CVBSOA)
  RCONST(85) = (RATE_CVBSOA)
  RCONST(86) = (RATE_CVBSOA)
  RCONST(87) = (2.3D-11)
  RCONST(88) = (ARR2(1.64D-11,125.0_dp,TEMP))
  RCONST(89) = (ARR2(8.64D-13,-450.0_dp,TEMP))
      
END SUBROUTINE Update_RCONST

! End of Update_RCONST function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Update_PHOTO - function to update photolytical rate constants
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Update_PHOTO ( )


   USE redhc_made_soa_vbs_Global

  RCONST(1) = (j(Pj_o31d)*usro3j2oh(temp,c_m,c_h2o))
  RCONST(2) = (j(Pj_no2))
  RCONST(3) = (j(Pj_n2o5))
  RCONST(4) = (j(Pj_hno3))
  RCONST(5) = (j(Pj_no3o))
  RCONST(6) = (j(Pj_hno4))
  RCONST(7) = (j(Pj_ch2or))
  RCONST(8) = (j(Pj_ch2om))
  RCONST(9) = (j(Pj_h2o2))
  RCONST(10) = (j(Pj_ch3cho))
  RCONST(11) = (j(Pj_ch3cocho))
  RCONST(12) = (j(Pj_pan))
  RCONST(13) = (j(Pj_ch3o2h))
  RCONST(14) = (j(Pj_ch3o2h))
      
END SUBROUTINE Update_PHOTO

! End of Update_PHOTO function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE redhc_made_soa_vbs_Rates

